version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8111"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8088:8088"
